### ISSUE TITLE
Kubernetes job board

### ISSUE THREAD

**Issue by danielepolencic** [rootsongjc/awesome-cloud-native#48]
I'd like to list [Kube.Careers](https://kube.careers) a Kubernetes job board that

1. is curated only with Kubernetes jobs.
2. there are clear salary ranges.
3. you apply directly to companies.

I was planning to add it to the "Community" section.

I understand that this might controversial, so happy to close this ticket if not relevant.

**Comment by rootsongjc** [comment]
I don't think this quite fits in this list. Thank you for your submission.
