### ISSUE TITLE
Can you add tenv?

### ISSUE THREAD

**Issue by kvendingoldo** [rootsongjc/awesome-cloud-native#80]
https://github.com/tofuutils/tenv is OpenTofu, Terraform, Terragrunt, and Atmos version manager, written in Go. For now it's the only one version manager that smartly support OpenTofu/Terraform/Terragrunt and Atmos in one tool.

**Comment by rootsongjc** [comment]
Yes, which category would you recommend putting it under? I can add or you can submit a PR

**Comment by kvendingoldo** [comment]
I think, it can be added near to Terraform, to Application Delivery section.

**Comment by rootsongjc** [comment]
Added, close this issue.

**Comment by kvendingoldo** [comment]
thanks!
